apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - route.yaml

images:
  - name: quarkus
    newName: image-registry.openshift-image-registry.svc:5000/kcd45/code-with-quarkus-kcd45
    newTag: 0.0.0
